[package]
name = "dure-app"
version = "0.1.0"
description = "A dure App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "tauri_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rust-argon2 = "2.1"
tauri-plugin-os = "2"
tauri-plugin-notification = "2"
tauri-plugin-log = "2"
tauri-plugin-stronghold = "2.0.1"
tauri-plugin-store = "2"
# tauri-plugin-system-info = "2.0.8"
# tauri-plugin-mqtt = { git = "https://github.com/bignikescar/tauri-plugin-mqtt", branch = "android" }

# openssl = { version = "0.10", features = ["vendored"] }
# openssl-sys = { version = "0.9", featuers = ["vendored"] }
# reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
